### ISSUE TITLE
CourseDetail could be RetrieveUpdateDestroyAPIView

### ISSUE THREAD

**Issue by emerline-pavelsushko** [byitema/classroom-api#10]
https://github.com/byitema/classroom-api/blob/223208f61ca690e87d1301a3c2062c8760601255/api/view/course.py#L32

CourseDetail view look like very good case to use`RetrieveUpdateDestroyAPIView ` base class for easier config of serialiser and avoid coding Response directly

**Comment by byitema** [comment]
CourseDetail is an instance of RetrieveUpdateDestroyAPIView now
