### ISSUE TITLE
Adding and removing teachers and students to/from course

### ISSUE THREAD

**Issue by emerline-pavelsushko** [byitema/classroom-api#11]
https://github.com/byitema/classroom-api/blob/223208f61ca690e87d1301a3c2062c8760601255/api/view/course.py#L86

Adding or removing teachers and students to/from course might be much easier (and in more RESTful way) done by updating the course object with fields `teachers` and `students`. And it will also help with duplicate code under `put` an `delete` methods

**Comment by byitema** [comment]
now you can update/create course object with teachers and students fields
