### ISSUE TITLE
related_name usage

### ISSUE THREAD

**Issue by emerline-pavelsushko** [byitema/classroom-api#17]
https://github.com/byitema/classroom-api/blob/223208f61ca690e87d1301a3c2062c8760601255/api/models.py#L10
https://github.com/byitema/classroom-api/blob/223208f61ca690e87d1301a3c2062c8760601255/api/models.py#L11

related_name is used to have "reversed" queries - to have courses from either teachers or students. So it seems like the best case is to have `related_name='courses'` here

**Comment by byitema** [comment]
changed related_name to 'teachers_courses' and 'students_courses' (they can't be the same)
