### ISSUE TITLE
CourseList could be ListCreateAPIView

### ISSUE THREAD

**Issue by emerline-pavelsushko** [byitema/classroom-api#9]
https://github.com/byitema/classroom-api/blob/223208f61ca690e87d1301a3c2062c8760601255/api/view/course.py#L12

CourseList view look like very good case to use `ListCreateAPIView` base class for easier config of serialiser and avoid coding Response directly

**Comment by byitema** [comment]
CourseList is an instance of ListCreateAPIView now
